### ISSUE TITLE
'Invalid thread access' error popup displayed during a failed workspace import

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#51]
Update the import code to always throw an NPE or other runtime exception.
Someplace in BazelClasspathContainer is a good spot.

Currently that causes import to fail with cryptic "Invalid thread access" error popup.
The popup itself comes from BazelImportWizard.performFinish()

**Comment by plaird** [comment]
Solved by a pattern introduced in #99 to wrap the MessageDialog op in a delegation to the UI thread:

Display.getDefault().syncExec(new Runnable() {
            public void run() {
                MessageDialog.openError(Display.getDefault().getActiveShell(), "Error", "error message");
            }
        });

**Comment by plaird** [comment]
@dylanShark here is the last attempt to fix the Invalid Thread Access issue.

**Comment by DMX-DCardinal** [comment]
Still experiencing this issue. Any suggestions about the source of the error in the mean time?

**Comment by plaird** [comment]
Unfortunately, it is a generic error. If you launch Eclipse from a console window, there might be a stack trace written there that may be more helpful. We hope to fix this soon.
